version: "2"
run:
  concurrency: 16
  go: "1.24"
  issues-exit-code: 1
  tests: true
linters:
  enable:
    - copyloopvar
    - gochecksumtype
    - goconst
    - misspell
    - revive
    - unconvert
  disable:
    - unparam
    - unused
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/grafana/loki/pkg
        - github.com/grafana/loki/tools
        - github.com/grafana/lambda-promtail/pkg
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
